name: deploy to github page

on:
  watch:
    types: [started]

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Build and Deploy
          uses: jeoy/github-deploy-actions@v1.0.1
          env:
            COMMIT_EMAIL: ${{ secrets.COMMIT_EMAIL }} 
            ACCESS_TOKEN: ${{ secrets.EXAMPLE_TOKEN }}
            BASE_BRANCH: dev
            DEPLOY_BRANCH: master
            BUILD_SCRIPT: yarn && yarn build
            FOLDER: docs
