name: Deploy to GitHub Pages
on:
  watch:
    types: [started]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: master
        FOLDER: docs
        GITHUB_TOKEN: ${{ secrets.EXAMPLE_TOKEN }}
